sources:
  pubsub_in1:
    type: gcp_pubsub
    project: "neon-circle-400322"
    subscription: "input-sub-1"
    decoding:
      codec: "json"
  pubsub_in2:
    type: gcp_pubsub
    project: "neon-circle-400322"
    subscription: "input-sub-2"
    decoding:
      codec: "json"

transforms:

