appenders:
  console_stdout:
    kind: console
    encoder:
      pattern: "{h({beaver_config(%Y-%m-%beaver_config %H:%M:%S)(utc)} - {l}: {m}{n})}"
  file_stdout:
    kind: file
    path: ../BeaverConfig/log/log1.log
    encoder:
      pattern: "{h({beaver_config(%Y-%m-%beaver_config %H:%M:%S)(utc)} - {l}: {m}{n})}"
root:
  level: debug
  appenders:
    - console_stdout
    - file_stdout